PORT: ${PORT}

REDIS_ADDR: ${REDIS_ADDR}
REDIS_PASS: ${REDIS_PASS}

KAFKA_BROKERS: ${KAFKA_BROKERS}
KAFKA_TOPIC: ${KAFKA_TOPIC}
KAFKA_PRODUCER_TOPIC: ${KAFKA_PRODUCER_TOPIC}
KAFKA_CONSUMER_GROUP: ${KAFKA_CONSUMER_GROUP}
KAFKA_CONSUMER_TOPICS: ${KAFKA_CONSUMER_TOPICS}

KEYCLOAK_URL: ${KEYCLOAK_URL}
KEYCLOAK_REALM: ${KEYCLOAK_REALM}

POSTGRES_HOST: ${POSTGRES_HOST}
POSTGRES_PORT: ${POSTGRES_PORT}
POSTGRES_USER: ${POSTGRES_USER}
POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}