// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.3
// source: pkg/proto/post.proto

package postpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostRequest) Reset() {
	*x = GetPostRequest{}
	mi := &file_pkg_proto_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostRequest) ProtoMessage() {}

func (x *GetPostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostRequest.ProtoReflect.Descriptor instead.
func (*GetPostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_post_proto_rawDescGZIP(), []int{0}
}

func (x *GetPostRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type GetPostByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByUserIdRequest) Reset() {
	*x = GetPostByUserIdRequest{}
	mi := &file_pkg_proto_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByUserIdRequest) ProtoMessage() {}

func (x *GetPostByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetPostByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_post_proto_rawDescGZIP(), []int{1}
}

func (x *GetPostByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetPostResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId    string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Optional fields
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	LikeCount     int64                  `protobuf:"varint,7,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	RepostCount   int64                  `protobuf:"varint,8,opt,name=repost_count,json=repostCount,proto3" json:"repost_count,omitempty"`
	CommentCount  int64                  `protobuf:"varint,9,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	Media         []string               `protobuf:"bytes,10,rep,name=media,proto3" json:"media,omitempty"`
	Files         []string               `protobuf:"bytes,11,rep,name=files,proto3" json:"files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostResponse) Reset() {
	*x = GetPostResponse{}
	mi := &file_pkg_proto_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostResponse) ProtoMessage() {}

func (x *GetPostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostResponse.ProtoReflect.Descriptor instead.
func (*GetPostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_post_proto_rawDescGZIP(), []int{2}
}

func (x *GetPostResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPostResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetPostResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetPostResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *GetPostResponse) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *GetPostResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetPostResponse) GetLikeCount() int64 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *GetPostResponse) GetRepostCount() int64 {
	if x != nil {
		return x.RepostCount
	}
	return 0
}

func (x *GetPostResponse) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *GetPostResponse) GetMedia() []string {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *GetPostResponse) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_pkg_proto_post_proto protoreflect.FileDescriptor

const file_pkg_proto_post_proto_rawDesc = "" +
	"\n" +
	"\x14pkg/proto/post.proto\x12\x04post\x1a\x1fgoogle/protobuf/timestamp.proto\")\n" +
	"\x0eGetPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\tR\x06postId\"1\n" +
	"\x16GetPostByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x98\x03\n" +
	"\x0fGetPostResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"like_count\x18\a \x01(\x03R\tlikeCount\x12!\n" +
	"\frepost_count\x18\b \x01(\x03R\vrepostCount\x12#\n" +
	"\rcomment_count\x18\t \x01(\x03R\fcommentCount\x12\x14\n" +
	"\x05media\x18\n" +
	" \x03(\tR\x05media\x12\x14\n" +
	"\x05files\x18\v \x03(\tR\x05files2\x85\x01\n" +
	"\vPostService\x126\n" +
	"\aGetPost\x12\x14.post.GetPostRequest\x1a\x15.post.GetPostResponse\x12>\n" +
	"\x0fGetPostByUserId\x12\x14.post.GetPostRequest\x1a\x15.post.GetPostResponseB\x18Z\x16/pkg/proto/post;postpbb\x06proto3"

var (
	file_pkg_proto_post_proto_rawDescOnce sync.Once
	file_pkg_proto_post_proto_rawDescData []byte
)

func file_pkg_proto_post_proto_rawDescGZIP() []byte {
	file_pkg_proto_post_proto_rawDescOnce.Do(func() {
		file_pkg_proto_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_post_proto_rawDesc), len(file_pkg_proto_post_proto_rawDesc)))
	})
	return file_pkg_proto_post_proto_rawDescData
}

var file_pkg_proto_post_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_proto_post_proto_goTypes = []any{
	(*GetPostRequest)(nil),         // 0: post.GetPostRequest
	(*GetPostByUserIdRequest)(nil), // 1: post.GetPostByUserIdRequest
	(*GetPostResponse)(nil),        // 2: post.GetPostResponse
	(*timestamppb.Timestamp)(nil),  // 3: google.protobuf.Timestamp
}
var file_pkg_proto_post_proto_depIdxs = []int32{
	3, // 0: post.GetPostResponse.created_at:type_name -> google.protobuf.Timestamp
	3, // 1: post.GetPostResponse.updated_at:type_name -> google.protobuf.Timestamp
	3, // 2: post.GetPostResponse.deleted_at:type_name -> google.protobuf.Timestamp
	0, // 3: post.PostService.GetPost:input_type -> post.GetPostRequest
	0, // 4: post.PostService.GetPostByUserId:input_type -> post.GetPostRequest
	2, // 5: post.PostService.GetPost:output_type -> post.GetPostResponse
	2, // 6: post.PostService.GetPostByUserId:output_type -> post.GetPostResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_post_proto_init() }
func file_pkg_proto_post_proto_init() {
	if File_pkg_proto_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_post_proto_rawDesc), len(file_pkg_proto_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_post_proto_goTypes,
		DependencyIndexes: file_pkg_proto_post_proto_depIdxs,
		MessageInfos:      file_pkg_proto_post_proto_msgTypes,
	}.Build()
	File_pkg_proto_post_proto = out.File
	file_pkg_proto_post_proto_goTypes = nil
	file_pkg_proto_post_proto_depIdxs = nil
}
