port: ${PORT}
keycloak_url: ${KEYCLOAK_URL}
keycloak_realm: ${KEYCLOAK_REALM}
keycloak_client_id: ${KEYCLOAK_CLIENT_ID}
keycloak_client_secret: ${KEYCLOAK_CLIENT_SECRET}
keycloak_cert_path: ${KEYCLOAK_CERT_PATH}
kafka_brokers:
  - ${KAFKA_BROKERS}
kafka_topic: ${KAFKA_TOPIC}
