apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: go-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.3.1
          args: ["start-dev"]
          ports:
            - containerPort: 8080
            - containerPort: 8443
          env:
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://keycloak-postgres-0.keycloak-postgres.go-project.svc.cluster.local:5432/keycloakdb
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: keycloakpass
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: go-project
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
  type: NodePort