apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
  namespace: go-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
        - name: post-service
          image: sayansayan123/go-project-post-service:1.1
          ports:
            - containerPort: 8089
          env:
            - name: PORT
              value: "8089"

            - name: ACCESS_KEY
              value: "gtrD94xFOKScmHDxVHCr"
            - name: SECRET_KEY
              value: "18IWfkPpapLpWZh9yamEiAv7dsqIlGF4fezdXWft"
            - name: MINIO_BUCKET
              value: "go-project"
            - name: MINIO_HOST
              value: "minio.go-project.svc.cluster.local"
            - name: MINIO_PORT
              value: "9000"

            - name: REDIS_ADDR
              value: "redis.go-project.svc.cluster.local:6379"
            - name: REDIS_PASS
              value: ""

            - name: KAFKA_BROKERS
              value: "kafka.go-project.svc.cluster.local:29092"
            - name: KAFKA_TOPIC
              value: "posts-events"

            - name: MONGO_URI
              value: "mongodb://mongo:mongopass@mongo.go-project.svc.cluster.local:27017/?authSource=admin"
            - name: MONGO_DB_NAME
              value: "go-project"

            - name: KEYCLOAK_REALM
              value: "go-project"
            - name: KEYCLOAK_URL
              value: "http://keycloak.go-project.svc.cluster.local:8080"

          resources:
            requests:
              cpu: "100"
              memory: "128Mi"
            limits:
              cpu: "200"
              memory: "256Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: go-project
spec:
  type: NodePort

  selector:
    app: post-service
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30089

